#!/bin/bash

value=$1

if [[ $value == "--help" || $value == "-help" || $value == "-h" ]]; then
	cat /opt/mybatop/mainscript/help.txt
elif [[ $value == "--html" || $value == "-html" ]]; then
	export present_dir=$(pwd)
	bash /opt/mybatop/analyze/generate-html.sh
	cp /opt/mybatop/analyze/merge.html $present_dir/battery-report.html
	echo "The battery-report.html is generated and it is saved to $present_dir"
elif [[ $value == "--version" || $value == "-version" || $value == "-v" ]]; then
	echo -e "mybatop\n version:1.0.0"
else
	echo "Invalid option"
fi
