#!/bin/bash

if [[ $1 == "--help" || $1 == "-help" || $1 == "--h" || $1 == "-h" ]]; then
  cat /opt/mybatop/scripts/runscript/help.txt

elif [[ $1 == "report" ]]; then

  if [[ $2 == "--html" ]]; then
    present_dir=$(pwd)
    export present_dir
    bash /opt/mybatop/analyze/generate-html.sh
    cp /opt/mybatop/analyze/merge.html "$present_dir"/battery-report.html
    echo "The battery-report.html is generated and it is saved to $present_dir"

  elif [[ $2 == "--json" ]]; then
    present_dir=$(pwd)
    export present_dir
    bash /opt/mybatop/analyze/generate-json.sh
    cp /opt/mybatop/analyze/pythonscripts/battery_report.json "$present_dir"/battery-report.json
    rm -rf /opt/mybatop/analyze/pythonscripts/battery_report.json
    echo "The battery-report.json is generated and it is saved to $present_dir"

  elif [[ $2 == "--xml" ]]; then
    present_dir=$(pwd)
    export present_dir
    bash /opt/mybatop/analyze/generate-xml.sh
    cp /opt/mybatop/analyze/pythonscripts/battery_report.xml "$present_dir"/battery-report.xml
    rm -rf /opt/mybatop/analyze/pythonscripts/battery_report.xml
    echo "The battery-report.xml is generated and it is saved to $present_dir"

  elif [[ $2 == "-C" || $2 == "--class" ]]; then

    bash /opt/mybatop/generate_data/generate_csv.sh
    cp /opt/mybatop/data/final.csv /opt/mybatop/analyze/pythonscripts/data.csv
    user_dir=$(pwd)
    cd /opt/mybatop/analyze/pythonscripts/ || exit

    if [[ $3 == "recent-usage" ]]; then

      PROGRAM="analyzers.py"

      if [[ $4 == "--html" ]]; then
        python3 $PROGRAM --html
        cp a.html $user_dir/recent-usage.html
        rm -rf a.html
      elif [[ $4 == "--csv" ]]; then
        python3 $PROGRAM --csv
      elif [[ $4 == "--json" ]]; then
        python3 $PROGRAM --json
      elif [[ $4 == "--xml" ]]; then
        python3 $PROGRAM --xml
      else
        echo "$4 is a invalid option. Check 'mybatop --h' for help."
      fi

    elif [[ $3 == "tech-spec" || $3 == "tech-specification" ]]; then

      PROGRAM="/opt/mybatop/analyze/pythonscripts/tech_spec.py"

      if [[ $4 == "--html" ]]; then
        python3 $PROGRAM --html
      elif [[ $4 == "--csv" ]]; then
        python3 $PROGRAM --csv
      elif [[ $4 == "--json" ]]; then
        python3 $PROGRAM --json
      elif [[ $4 == "--xml" ]]; then
        python3 $PROGRAM --xml
      else
        echo "$4 is a invalid option. Check 'mybatop --h' for help."
      fi

    elif [[ $3 == "average-capacity" ]]; then

      PROGRAM="/opt/mybatop/analyze/pythonscripts/dchar.py"

      if [[ $4 == "--html" ]]; then
        python3 $PROGRAM --html
      elif [[ $4 == "--csv" ]]; then
        python3 $PROGRAM --csv
      elif [[ $4 == "--json" ]]; then
        python3 $PROGRAM --json
      elif [[ $4 == "--xml" ]]; then
        python3 $PROGRAM --xml
      else
        echo "$4 is a invalid option. Check 'mybatop --h' for help."
      fi

    elif [[ $3 == "battery-capacity-history" || $3 == "batcaphis" ]]; then

      PROGRAM="/opt/mybatop/analyze/pythonscripts/battery_capacity_history.py"

      if [[ $4 == "--html" ]]; then
        python3 $PROGRAM --html
      elif [[ $4 == "--csv" ]]; then
        python3 $PROGRAM --csv
      elif [[ $4 == "--json" ]]; then
        python3 $PROGRAM --json
      elif [[ $4 == "--xml" ]]; then
        python3 $PROGRAM --xml
      else
        echo "$4 is a invalid option. Check 'mybatop --h' for help."
      fi

    elif [[ $3 == "cycle-count" ]]; then

      PROGRAM="/opt/mybatop/analyze/pythonscripts/cycle_counts.py"

      if [[ $4 == "--html" ]]; then
        python3 $PROGRAM --html
      elif [[ $4 == "--csv" ]]; then
        python3 $PROGRAM --csv
      elif [[ $4 == "--json" ]]; then
        python3 $PROGRAM --json
      elif [[ $4 == "--xml" ]]; then
        python3 $PROGRAM --xml
      else
        echo "$4 is a invalid option. Check 'mybatop --h' for help."
      fi

    elif [[ $3 == "battery-health" ]]; then

      PROGRAM="/opt/mybatop/analyze/pythonscripts/battery_health.py"

      if [[ $4 == "--html" ]]; then
        python3 $PROGRAM --html
      elif [[ $4 == "--csv" ]]; then
        python3 $PROGRAM --csv
      elif [[ $4 == "--json" ]]; then
        python3 $PROGRAM --json
      elif [[ $4 == "--xml" ]]; then
        python3 $PROGRAM --xml
      else
        echo "$4 is a invalid option. Check 'mybatop --h' for help."
      fi

    elif [[ $3 == "battery-usage-activity" || $3 == "batuseact" ]]; then

      PROGRAM="/opt/mybatop/analyze/pythonscripts/battery_activity.py"

      if [[ $4 == "--html" ]]; then
        python3 $PROGRAM --html
      elif [[ $4 == "--csv" ]]; then
        python3 $PROGRAM --csv
      elif [[ $4 == "--json" ]]; then
        python3 $PROGRAM --json
      elif [[ $4 == "--xml" ]]; then
        python3 $PROGRAM --xml
      else
        echo "$4 is a invalid option. Check 'mybatop --h' for help."
      fi
    else
      echo "$3 is a invalid option. Check 'mybatop --h' for help."
    fi
  else
    echo "$2 is a invalid option. Check 'mybatop --h' for help."
  fi
  rm -rf /opt/mybatop/analyze/pythonscripts/data.csv

elif [[ $1 == "data" ]]; then

  if [[ $2 == "--xml" ]]; then
    python3 /opt/mybatop/generate_data/generate_xml.py

  elif [[ $2 == "--csv" ]]; then
    python3 /opt/mybatop/generate_data/generate_csv.py
    cp /opt/mybatop/final.csv "$(pwd)/data.csv"
    echo "The data.csv is generated and it is saved to $(pwd)"

  elif [[ $2 == "--json" ]]; then
    python3 /opt/mybatop/generate_data/generate_json.py
  fi
elif [[ $1 == "--version" || $1 == "-version" || $1 == "-v" ]]; then
  echo -e "mybatop\n version:1.0.0"
else
  echo "Invalid option"
fi
