name: Build Packages for various Distros
on:
    workflow_dispatch:
jobs:
    debian-package:
        runs-on: ubuntu-latest
        env:
            APP_VERSION: "2.0.0"
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setting Up for building packages
              run: |
                sudo apt-get install -y dpkg-dev ninja-build devscripts meson
                cp src/mybatop mybatop-${{APP_VERSION}}
                tar -cvf mybatop-${{APP_VERSION}}.tar.gz mybatop-${{APP_VERSION}}/
                rm -rf mybatop-${{APP_VERSION}}
                
            - name: Build Debian Package (.deb)
              run: |
                mkdir mybatop-${{APP_VERSION}}
                cd mybatop-${{APP_VERSION}}
                mkdir -p {DEBIAN,opt/,usr/bin/,etc/systemd/system/}

                control=$(cat build/Debian/control)
                eval "echo \"$control\"" >> DEBIAN/control
                cp build/Debian/postinst DEBIAN/postinst
                cp build/Debian/postrm DEBIAN/postrm
                cp build/Debian/prerm DEBIAN/prerm

                cp -r src/* mybatop-${{APP_VERSION}}/opt/
                cp -r src/filesystemd/* mybatop-1.0.0/etc/systemd/system/
                cd ..

                dpkg-dev --build mybatop-${{APP_VERSION}}


            - name: Upload artifacts
              uses: actions/upload-artifact@v4.6.1
              with:
                  name: deb-artifact
                  path: mybatop-${{APP_VERSION}}.deb

    rpm-package:
        runs-on: ubuntu-latest
        env:
            APP_VERSION: "2.0.0"
        container: fedora-latest
        steps:
            - name: Build Fedora/RedHat/OpenSUSE packages (.rpm)
              run: |
                sudo dnf install -y rpmdevtools rpm-build rpmlint
                mkdir -p rpmbuild/{SOURCES,SPECS,BUILDS,RPMS,SRPMS}
                cp mybatop-${{APP_VERSION}} rpmbuild/SOURCES
                specs=$(cat build/mybatop.spec)
                eval "echo \"$specs\"" > rpmbuild/SPECS/mybatop.spec
                
                cd rpmbuild/SPECS
                rpmbuild -ba mybatop.spec

            - name: Upload Artifacts
              uses: actions/upload-artifacts@4.6.1

    upload-artifacts:
    needs: [debian-package, rpm-package]
    runs-on: ubuntu-latest
    env:
      APP_VERSION: "2.0.0"
    steps:
      - name: Download deb file
        uses: actions/download-artifact@v4.2.0
        with:
          name: deb-artifact
          path: artifacts/*.deb
      - name: Download rpm file
        uses: actions/download-artifact@v4.2.0
        with:
          name: rpm-artifact
          path: artifacts/*.rpm
      - name: Upload to releases
        uses: ncipollo/release-action@v1.16.0
        with:
          artifacts: artifacts/*.deb, artifacts/*.rpm
          body: |
            Testing build for .rpm and .deb packages
          tag: ${{APP_VERSION}}
          token: ${{secrets.TOKENS}}
