name: Testing *.py files
on:
  push:
    branches: dev
  pull_request:
    branches: dev

jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: ["ubuntu:latest","fedora:latest","archlinux:latest"]
        python_version: ["3.10","3.11","3.12","3.13"]
    container:
        image: ${{matrix.os}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup UV
        uses: astral-sh/setup-uv@v5
        with:
          version: latest
          python-version: ${{matrix.python_version}}

      - name: Install python packages
        run: |
          uv pip install pandas plotly ruff

      - name: Start Linting
        run: |
          cd src/mybatop/analyze/pythonscripts/
          ruff check *.py
          cd ../../generate_data/
          ruff check *.py


